"""Public API for the coalescence-curvature analysis project."""

from .analysis import (
    AnalysisConfig,
    BoundaryPoints,
    FrameDiagnostic,
    FrameMeasurement,
    LocalFit,
    analyze_frame,
    analyze_tiff,
    extract_boundaries,
    fit_local_boundary,
    iter_tiff_frames,
    plot_frame_diagnostic,
    plot_time_series,
    read_tiff_frame,
    save_measurements_csv,
    select_local_window,
    summarize_measurements,
    tiff_metadata,
)

__all__ = [
    "AnalysisConfig",
    "BoundaryPoints",
    "FrameDiagnostic",
    "FrameMeasurement",
    "LocalFit",
    "analyze_frame",
    "analyze_tiff",
    "extract_boundaries",
    "fit_local_boundary",
    "iter_tiff_frames",
    "plot_frame_diagnostic",
    "plot_time_series",
    "read_tiff_frame",
    "save_measurements_csv",
    "select_local_window",
    "summarize_measurements",
    "tiff_metadata",
]
